services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # UI
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

volumes:
  minio-data:
