version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  minio-init:
    image: minio/mc
    container_name: init-carpetas
    depends_on:
      - minio
    volumes:
      - ./init-minio.sh:/init.sh
      - ./empty-dir:/empty-dir
    entrypoint: ["/bin/sh", "/init.sh"]

  minio-carga-masiva:
    image: minio/mc
    container_name: carga-masiva
    depends_on:
      - minio
    volumes:
      - ./carga-masiva.sh:/carga-masiva.sh
      - ./data-to-upload:/data-to-upload
    entrypoint: [ "sh", "-c", "/carga-masiva.sh" ]
    networks:
      - default
    restart: "no"

volumes:
  minio-data:
