version: '3.8'

services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - fusaroadsred

  minio-init:
    image: minio/mc
    container_name: init-carpetas
    depends_on:
      - minio
    volumes:
      - ./init-minio.sh:/init.sh  # Asegurar que el 'Select End of Line Secuence = LF en el .sh'
      - ./empty-dir:/empty-dir
    entrypoint: ["/bin/sh", "/init.sh"]
    networks:
      - fusaroadsred

volumes:
  minio-data:

networks:
  fusaroadsred:
    external: true